# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.User_points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.User_points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.User_points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_points',
            name='height',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user_points',
            name='photo',
            field=models.ImageField(default='/static/sample.png', height_field='height', upload_to=b'', width_field='width'),
        ),
        migrations.AddField(
            model_name='user_points',
            name='width',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.TextField(),
        ),
    ]
